services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - PORT=${FRONT_PORT}
      - REACT_APP_BACK=${BACK_URL}
    ports:
      - 8080:8080
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: dev
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '9999:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

